version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: dailydb-backend
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
    restart: unless-stopped
    labels:
      - autoheal=true

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: dailydb-frontend
    env_file:
      - .env
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    environment:
      API_URL: ${API_URL}
      FRONTEND_PORT: ${FRONTEND_PORT}
      NEW_RELIC_LICENSE_KEY: ${NEW_RELIC_LICENSE_KEY}
      NEW_RELIC_APP_NAME: ${NEW_RELIC_APP_NAME}
      NEW_RELIC_LOG_LEVEL: ${NEW_RELIC_LOG_LEVEL}
      NEW_RELIC_NO_CONFIG_FILE: ${NEW_RELIC_NO_CONFIG_FILE}
    restart: unless-stopped
    depends_on:
      - backend
    labels:
      - autoheal=true

  autoheal:
    image: willfarrell/autoheal
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - AUTOHEAL_INTERVAL=5
      - AUTOHEAL_START_PERIOD=120
      - CURL_TIMEOUT=5
      - AUTOHEAL_CONTAINER_LABEL=autoheal
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
