// Comprehensive Permissions List for Daily Dashboard
// This includes granular permissions for every UI element and feature

export const COMPREHENSIVE_PERMISSIONS = {
    // ===== DASHBOARD OVERVIEW PERMISSIONS =====
    dashboard_view_overview_tab: 'View Overview Tab',
    dashboard_view_recruiter_stats_tab: 'View Recruiter Stats Tab',
    dashboard_view_expert_stats_tab: 'View Expert Stats Tab',
    dashboard_view_management_reports_tab: 'View Management Reports Tab',
    dashboard_change_date_basis: 'Change Date Basis (Interview/Received)',
    dashboard_change_date_mode: 'Change Date Mode (Month/Week/Day)',
    dashboard_view_total_candidates_card: 'View Total Candidates Card',
    dashboard_view_total_interviews_card: 'View Total Interviews Card',
    dashboard_view_completed_interviews_card: 'View Completed Interviews Card',
    dashboard_view_pending_tasks_card: 'View Pending Tasks Card',

    // ===== TASKS PAGE PERMISSIONS =====
    tasks_view_page: 'View Tasks Page',
    tasks_view_subject_column: 'View Subject Column',
    tasks_view_candidate_column: 'View Candidate Name Column',
    tasks_view_expert_column: 'View Expert/Suggested Expert Column',
    tasks_view_resume_column: 'View Resume Column',
    tasks_view_date_column: 'View Date Column',
    tasks_view_status_column: 'View Status Column',
    tasks_view_recruiter_column: 'View Recruiter Column',
    tasks_view_actions_column: 'View Actions Column',

    tasks_filter_by_status: 'Filter Tasks by Status',
    tasks_filter_by_candidate: 'Filter by Candidate Name',
    tasks_filter_by_recruiter: 'Filter by Recruiter',
    tasks_filter_by_expert: 'Filter by Expert',
    tasks_filter_by_date_range: 'Filter by Date Range',
    tasks_filter_by_team_lead: 'Filter by Team Lead',

    tasks_change_status: 'Change Task Status',
    tasks_assign_expert: 'Assign Expert to Task',
    tasks_view_suggestions: 'View Suggestions',
    tasks_join_meeting: 'Join Meeting',
    tasks_copy_meeting_link: 'Copy Meeting Link',
    tasks_create_meeting: 'Create Online Meeting',
    tasks_clone_support: 'Clone Support Task',
    tasks_request_mock: 'Request Mock Interview',
    tasks_generate_thanks_mail: 'Generate Thanks Mail',
    tasks_generate_interviewer_questions: 'Generate Interviewer Questions',
    tasks_delete_task: 'Delete Task',
    tasks_view_transcript: 'View Transcript Status',
    tasks_toggle_subject_display: 'Toggle Subject Display',
    tasks_assessment_support: 'Access Assessment Support',

    // ===== BRANCH CANDIDATES PERMISSIONS ===== 
    candidates_view_page: 'View Branch Candidates Page',
    candidates_view_list: 'View Candidates List',
    candidates_view_name_column: 'View Name Column',
    candidates_view_email_column: 'View Email Column',
    candidates_view_contact_column: 'View Contact Column',
    candidates_view_technology_column: 'View Technology Column',
    candidates_view_expert_column: 'View Expert Column',
    candidates_view_recruiter_column: 'View Recruiter Column',
    candidates_view_status_column: 'View Status Column',
    candidates_view_interview_date_column: 'View Interview Date Column',
    candidates_view_actions_column: 'View Actions Column',

    candidates_create_new: 'Create New Candidate',
    candidates_edit_any: 'Edit Any Candidate',
    candidates_edit_own: 'Edit Own Candidates Only',
    candidates_edit_name: 'Edit Candidate Name',
    candidates_edit_email: 'Edit Candidate Email',
    candidates_edit_contact: 'Edit Contact Number',
    candidates_edit_technology: 'Edit Technology',
    candidates_edit_expert: 'Change Assigned Expert',
    candidates_edit_recruiter: 'Change Recruiter',
    candidates_edit_status: 'Edit Candidate Status',
    candidates_edit_interview_date: 'Edit Interview Date',
    candidates_delete: 'Delete Candidate',
    candidates_export: 'Export Candidates',
    candidates_import: 'Import Candidates',
    candidates_view_resume: 'View Resume',
    candidates_upload_resume: 'Upload Resume',
    candidates_send_reminder: 'Send Reminder',
    candidates_view_history: 'View Candidate History',
    candidates_start_tour: 'Start Driver Tour',

    candidates_filter_by_status: 'Filter by Status',
    candidates_filter_by_recruiter: 'Filter by Recruiter',
    candidates_filter_by_expert: 'Filter by Expert',
    candidates_filter_by_technology: 'Filter by Technology',
    candidates_filter_by_date_range: 'Filter by Date Range',
    candidates_search: 'Search Candidates',

    // ===== RESUME UNDERSTANDING PERMISSIONS =====
    resume_view_page: 'View Resume Understanding Page',
    resume_view_pending_tab: 'View Pending Tab',
    resume_view_inprogress_tab: 'View In Progress Tab',
    resume_view_completed_tab: 'View Completed Tab',
    resume_view_expert_column: 'View Expert Column',
    resume_view_candidate_column: 'View Candidate Column',
    resume_view_technology_column: 'View Technology Column',
    resume_view_status_column: 'View Status Column',
    resume_view_submitted_date_column: 'View Submitted Date Column',
    resume_view_actions_column: 'View Actions Column',

    resume_view_all_entries: 'View All Resume Entries',
    resume_view_own_entries: 'View Only Own Entries',
    resume_view_team_entries: 'View Team Entries',
    resume_update_status_any: 'Update Any Resume Status',
    resume_update_status_own: 'Update Own Resume Status',
    resume_view_details: 'View Resume Details',
    resume_download: 'Download Resume',
    resume_add_comments: 'Add Comments',
    resume_view_comments: 'View Comments',
    resume_assign_expert: 'Assign to Expert',
    resume_mark_complete: 'Mark as Complete',
    resume_reject: 'Reject Resume',

    resume_filter_by_status: 'Filter by Status',
    resume_filter_by_expert: 'Filter by Expert',
    resume_filter_by_technology: 'Filter by Technology',
    resume_filter_by_date: 'Filter by Date',
    resume_search: 'Search Resumes',

    // ===== USER MANAGEMENT PERMISSIONS =====
    users_view_page: 'View User Management Page',
    users_view_list: 'View Users List',
    users_view_name_column: 'View Name Column',
    users_view_email_column: 'View Email Column',
    users_view_role_column: 'View Role Column',
    users_view_team_lead_column: 'View Team Lead Column',
    users_view_manager_column: 'View Manager Column',
    users_view_status_column: 'View Status Column',
    users_view_actions_column: 'View Actions Column',

    users_create_new: 'Create New User',
    users_create_admin: 'Create Admin Users',
    users_create_manager: 'Create Manager Users',
    users_create_mm: 'Create MM Users',
    users_create_mam: 'Create MAM Users',
    users_create_mlead: 'Create MLead Users',
    users_create_lead: 'Create Lead Users',
    users_create_am: 'Create AM Users',
    users_create_recruiter: 'Create Recruiter Users',
    users_create_expert: 'Create Expert Users',

    users_edit_any: 'Edit Any User',
    users_edit_own: 'Edit Own Profile',
    users_edit_name: 'Edit User Name',
    users_edit_email: 'Edit User Email',
    users_edit_role: 'Edit User Role',
    users_edit_team_lead: 'Edit Team Lead Assignment',
    users_edit_manager: 'Edit Manager Assignment',
    users_edit_password: 'Edit User Password',
    users_change_own_password: 'Change Own Password',
    users_activate_deactivate: 'Activate/Deactivate Users',
    users_delete: 'Delete Users',
    users_view_activity_log: 'View User Activity Log',
    users_reset_password: 'Reset User Password',
    users_send_welcome_email: 'Send Welcome Email',

    users_filter_by_role: 'Filter by Role',
    users_filter_by_status: 'Filter by Active/Inactive',
    users_filter_by_team_lead: 'Filter by Team Lead',
    users_search: 'Search Users',

    // ===== REPORTS PERMISSIONS =====
    reports_view_page: 'View Reports Page',
    reports_view_performance: 'View Performance Reports',
    reports_view_activity: 'View Activity Reports',
    reports_view_analytics: 'View Analytics',
    reports_export: 'Export Reports',
    reports_schedule: 'Schedule Reports',
    reports_custom_date_range: 'Custom Date Range',

    // ===== ADMIN ALERTS PERMISSIONS =====
    alerts_view_page: 'View Admin Alerts Page',
    alerts_create: 'Create Alerts',
    alerts_edit: 'Edit Alerts',
    alerts_delete: 'Delete Alerts',
    alerts_view_history: 'View Alert History',

    // ===== PROFILE PERMISSIONS =====
    profile_view: 'View Own Profile',
    profile_edit: 'Edit Own Profile',
    profile_change_password: 'Change Own Password',
    profile_view_activity: 'View Own Activity',

    // ===== NOTIFICATIONS PERMISSIONS =====
    notifications_view: 'View Notifications',
    notifications_mark_read: 'Mark as Read',
    notifications_delete: 'Delete Notifications',
    notifications_configure: 'Configure Notification Preferences',

    // ===== SYSTEM PERMISSIONS =====
    system_view_whats_new: 'View Whats New',
    system_view_help: 'View Help',
    system_access_settings: 'Access System Settings',
    system_view_audit_log: 'View Audit Log',

    // ===== MEETING PERMISSIONS =====
    meetings_create: 'Create Meetings',
    meetings_edit: 'Edit Meetings',
    meetings_delete: 'Delete Meetings',
    meetings_join: 'Join Meetings',
    meetings_view_consent_banner: 'View Meeting Consent Banner',
    meetings_grant_consent: 'Grant Meeting Consent',
};

// Category mapping for UI organization
export const PERMISSION_CATEGORIES = {
    dashboard_overview: {
        label: 'Dashboard Overview',
        permissions: [
            'dashboard_view_overview_tab',
            'dashboard_view_recruiter_stats_tab',
            'dashboard_view_expert_stats_tab',
            'dashboard_view_management_reports_tab',
            'dashboard_change_date_basis',
            'dashboard_change_date_mode',
            'dashboard_view_total_candidates_card',
            'dashboard_view_total_interviews_card',
            'dashboard_view_completed_interviews_card',
            'dashboard_view_pending_tasks_card',
        ]
    },
    tasks_view: {
        label: 'Tasks - View & Columns',
        permissions: [
            'tasks_view_page',
            'tasks_view_subject_column',
            'tasks_view_candidate_column',
            'tasks_view_expert_column',
            'tasks_view_resume_column',
            'tasks_view_date_column',
            'tasks_view_status_column',
            'tasks_view_recruiter_column',
            'tasks_view_actions_column',
        ]
    },
    tasks_filters: {
        label: 'Tasks - Filters',
        permissions: [
            'tasks_filter_by_status',
            'tasks_filter_by_candidate',
            'tasks_filter_by_recruiter',
            'tasks_filter_by_expert',
            'tasks_filter_by_date_range',
            'tasks_filter_by_team_lead',
        ]
    },
    tasks_actions: {
        label: 'Tasks - Actions',
        permissions: [
            'tasks_change_status',
            'tasks_assign_expert',
            'tasks_view_suggestions',
            'tasks_join_meeting',
            'tasks_copy_meeting_link',
            'tasks_create_meeting',
            'tasks_clone_support',
            'tasks_request_mock',
            'tasks_generate_thanks_mail',
            'tasks_generate_interviewer_questions',
            'tasks_delete_task',
            'tasks_view_transcript',
            'tasks_toggle_subject_display',
            'tasks_assessment_support',
        ]
    },
    candidates_view: {
        label: 'Branch Candidates - View & Columns',
        permissions: [
            'candidates_view_page',
            'candidates_view_list',
            'candidates_view_name_column',
            'candidates_view_email_column',
            'candidates_view_contact_column',
            'candidates_view_technology_column',
            'candidates_view_expert_column',
            'candidates_view_recruiter_column',
            'candidates_view_status_column',
            'candidates_view_interview_date_column',
            'candidates_view_actions_column',
        ]
    },
    candidates_edit: {
        label: 'Branch Candidates - Edit',
        permissions: [
            'candidates_create_new',
            'candidates_edit_any',
            'candidates_edit_own',
            'candidates_edit_name',
            'candidates_edit_email',
            'candidates_edit_contact',
            'candidates_edit_technology',
            'candidates_edit_expert',
            'candidates_edit_recruiter',
            'candidates_edit_status',
            'candidates_edit_interview_date',
            'candidates_delete',
        ]
    },
    candidates_filters: {
        label: 'Branch Candidates - Filters & Actions',
        permissions: [
            'candidates_filter_by_status',
            'candidates_filter_by_recruiter',
            'candidates_filter_by_expert',
            'candidates_filter_by_technology',
            'candidates_filter_by_date_range',
            'candidates_search',
            'candidates_export',
            'candidates_import',
            'candidates_view_resume',
            'candidates_upload_resume',
            'candidates_start_tour',
        ]
    },
    resume_view: {
        label: 'Resume Understanding - View',
        permissions: [
            'resume_view_page',
            'resume_view_pending_tab',
            'resume_view_inprogress_tab',
            'resume_view_completed_tab',
            'resume_view_expert_column',
            'resume_view_candidate_column',
            'resume_view_technology_column',
            'resume_view_status_column',
            'resume_view_submitted_date_column',
            'resume_view_actions_column',
        ]
    },
    resume_actions: {
        label: 'Resume Understanding - Actions',
        permissions: [
            'resume_view_all_entries',
            'resume_view_own_entries',
            'resume_view_team_entries',
            'resume_update_status_any',
            'resume_update_status_own',
            'resume_view_details',
            'resume_download',
            'resume_add_comments',
            'resume_view_comments',
            'resume_assign_expert',
            'resume_mark_complete',
            'resume_reject',
        ]
    },
    resume_filters: {
        label: 'Resume Understanding - Filters',
        permissions: [
            'resume_filter_by_status',
            'resume_filter_by_expert',
            'resume_filter_by_technology',
            'resume_filter_by_date',
            'resume_search',
        ]
    },
    users_view: {
        label: 'User Management - View',
        permissions: [
            'users_view_page',
            'users_view_list',
            'users_view_name_column',
            'users_view_email_column',
            'users_view_role_column',
            'users_view_team_lead_column',
            'users_view_manager_column',
            'users_view_status_column',
            'users_view_actions_column',
        ]
    },
    users_create: {
        label: 'User Management - Create',
        permissions: [
            'users_create_new',
            'users_create_admin',
            'users_create_manager',
            'users_create_mm',
            'users_create_mam',
            'users_create_mlead',
            'users_create_lead',
            'users_create_am',
            'users_create_recruiter',
            'users_create_expert',
        ]
    },
    users_edit: {
        label: 'User Management - Edit',
        permissions: [
            'users_edit_any',
            'users_edit_own',
            'users_edit_name',
            'users_edit_email',
            'users_edit_role',
            'users_edit_team_lead',
            'users_edit_manager',
            'users_edit_password',
            'users_change_own_password',
            'users_activate_deactivate',
            'users_delete',
        ]
    },
    users_filters: {
        label: 'User Management - Filters & Actions',
        permissions: [
            'users_filter_by_role',
            'users_filter_by_status',
            'users_filter_by_team_lead',
            'users_search',
            'users_view_activity_log',
            'users_reset_password',
            'users_send_welcome_email',
        ]
    },
    other: {
        label: 'Other Permissions',
        permissions: [
            'reports_view_page',
            'reports_view_performance',
            'reports_view_activity',
            'reports_view_analytics',
            'reports_export',
            'alerts_view_page',
            'alerts_create',
            'alerts_edit',
            'profile_view',
            'profile_edit',
            'profile_change_password',
            'notifications_view',
            ' system_view_whats_new',
            'meetings_create',
            'meetings_join',
            'meetings_view_consent_banner',
        ]
    }
};
