# Upstream for Backend
upstream backend {
    include /etc/nginx/conf.d/upstreams/backend.active.conf;
}

# Upstream for Frontend
upstream frontend {
    include /etc/nginx/conf.d/upstreams/frontend.active.conf;
}

# Backend Gateway (Listens on internal 3004, exposed to host 3004)
server {
    listen 3004;
    location / {
        proxy_pass http://backend;
        # Standard proxy headers
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        
        # Websocket support
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
}

# Frontend Gateway (Listens on internal 8180, exposed to host 8180)
server {
    listen 8180;
    location / {
        proxy_pass http://frontend;
        # Standard proxy headers
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
